# Generated by Django 4.1 on 2022-08-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('markup', models.CharField(choices=[('bbcode', 'bbcode'), ('markdown', 'markdown')], default='bbcode', max_length=15, verbose_name='Markup')),
                ('body', models.TextField(verbose_name='Message')),
                ('body_html', models.TextField(verbose_name='HTML version')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='User IP')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['created'],
                'get_latest_by': 'created',
            },
        ),
    ]
