# Generated by Django 4.1 on 2022-08-20 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_post_table'),
        ('users', '0002_alter_profile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('sign', models.IntegerField(choices=[(1, 'PLUS'), (-1, 'MINUS')], default=0, verbose_name='Sign')),
                ('reason', models.TextField(max_length=1000, verbose_name='Reason')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputations_from', to=settings.AUTH_USER_MODEL, verbose_name='From')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.post', verbose_name='Post')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputations_to', to=settings.AUTH_USER_MODEL, verbose_name='To')),
            ],
            options={
                'verbose_name': 'Reputation',
                'verbose_name_plural': 'Reputations',
                'db_table': 'reputations',
                'unique_together': {('from_user', 'post')},
            },
        ),
    ]
