FORUM_LOGO_UPLOAD_TO = 'djbb/forum_logo'
FORUM_LOGO_WIDTH = 16
FORUM_LOGO_HEIGHT = 16
DEFAULT_MARKUP = 'bbcode'
SIGNATURE_MAX_LENGTH = 1024
AVATARS_UPLOAD_TO = 'djbb/avatars'
AVATAR_WIDTH = 60
AVATAR_HEIGHT = 60
